# Generated by Django 4.2 on 2023-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppCampSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sendgrid_api_key", models.CharField(max_length=255)),
                ("sender_email", models.CharField(max_length=255)),
                ("recipient_email", models.CharField(max_length=255)),
            ],
        ),
    ]
